tenant: "public"
namespace: "default"
name: "jdbc-clickhouse-sink"
inputs: ["persistent://public/default/weather-topic"]
sinkType: "jdbc-clickhouse"
configs:
  jdbcUrl: "jdbc:clickhouse://clickhouse:8123/default"
  tableName: "orders"
  useTransactions: "false"
